polls/urls.py
from django.conf.urls import patterns, include, url
from .import views

urlpatterns = patterns('',
    
    url(r'^$', views.index, name='index'),
    url(r'^form_upload/$', views.post_form_upload, name='post_form_upload'),
    url(r'^relay/$', views.my_view, name='my_view'),
    url(r'^swich/$', views.my_swich, name='my_swich'),

                       

)

smarthome/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^polls/', include('polls.urls', namespace="polls")),

    url(r'^admin/', include(admin.site.urls)),
)

polls/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django import forms

class PostForm(forms.Form):
    content = forms.CharField(max_length=200)
    created_at = forms.DateTimeField()

class RelayForm(forms.Form):
    relay = forms.CharField(max_length=200)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import loader
from .forms import PostForm, RelayForm
import requests


def index(request):
    
    return render(request, 'polls/index.html')


def post_form_upload(request):
    if request.method == 'GET':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            created_at = form.cleanded_data['created_at']
            post = m.Post.objects.create(content=content, created_at=created_at)
            return HttpResponseRedirect(reverse('post_detail', kqargs={'post_id': post.id}))

    return render(request, 'polls/post_form_upload.html', {'form': form})

def my_view(request):
    if request.method == 'POST':
        if form.is_valid():
            return HttpResposeRedirect(reverse('polls/index.html'))

    form = RelayForm()
    return render(request, 'polls/quad_relay.html', {})

def my_swich(request):
    r = requests.get("http://amur.info")
    return render(request, 'polls/my_swich.html', {})

polls/templates/polls/button.html
<title>Smarthome</title>
<style type="text/css">
    button.new {
        background: -moz-linear-gradient(#00BBD6, #EBFFFF);
        background: -webkit-gradient(linear, 0 0, 0 100%, from(#00BBD6), to(#EBFFFF));
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00BBD6', endColorstr='#EBFFFF');
        padding: 3px 7px;
        color: #333;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        border: 1px solid #666;
    }
</style>
<body>
    <h1>Main Page Smart Home</h1>
<p><a href="http://amur.info">Go to gadjet</a></p>
<form>
    <p><input type="button" value=" Button "></p>
    <p><button class="new">Button</button></p>
</form>

<p id="demo" onclick="myFunction()">Click me to change my text color.</p>

<script>
    function myFunction() {
        document.getElementById("demo").style.color = "red";
    }
</script>
</body>

polls/templates/polls/div.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<style type="text/css">
.block1 {
width:200px;
background: #ccc;
padding: 5px;
padding-right: 20px;
border: solid 1px black;
float: left;
}
    .block2 {
    width: 200px;
    background: #fc0;
    padding: 5px;
    border: solid 1px black;
    float: left;
    position: relative;
    top: 40px;
    left: -70px;
}
</style>
</head>
<body>

<div class="block1">Lorem ipsum dolor sit amet, consectetur
adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet
dolore magna aliguam erat volutpat.</div>

<div class="block2">Ut wisis enim ad minim veniam, quis nostrud
exerci tution ullamcorper suscipit lobortis nisl ut aliquip wx ea commodo consequat.</div>

</body>
</html>

polls/templates/polls/form.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Ter FROM, atribut action</title>
<style>
    h1 { font-size: 24 pt; margin-left: 30px; }
    p  { margin-left: 30px; }
    .my_button {
        width: 200px;
        height: 90px;
        background: red;
        border-radius: 10px;
    }
</style>
</head>
<body>
<h1>Test size</h1>
<form action="http://amur.info" enctype="text/plan">
<p><input type="submit" value="Write letter" class="my_button"></p>
</form>
</body>
</html>

polls/templates/polls/index.html
<title>Smarthome</title>

<body>
    <h1>Main Page Smart Home</h1>
<p><a href="http://amur.info">Go to gadjet</a></p>
</body>

polls/templates/polls/my_swich.html
<!DOCTYPE>
<html>
<head>

</head>
<body>
<h1>Quad Web Relay</h1>
<p>Hello World!</p>
</div>
</body>
</head>
</html>

polls/templates/polls/post_form_upload.html
<form action='' method='post'>
    {% csrf_token %}
    {{ form.as_p }}
<input type='submit' value='Submit' />
</form>

polls/templates/polls/quad_relay.html
<!DOCTYPE>
<html>
<head>

</head>
<body>
<h1>Quad Web Relay</h1>
<div>Relay 1:
    <form action="{% url 'polls:my_swich' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Toggle" id="toggle1" />
    </form>
</div>
</body>
</head>
</html>